export enum LoginState {
  PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
  SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN",
  LOCKED_OUT_STATE = "LOCKED_OUT_STATE",
  PROBLEM_STATE = "PROBLEM_STATE",
  PERFORMANCE_GLITCH = "PERFORMANCE_GLITCH",
}
